### ISSUE TITLE
no being able to execute this program

### ISSUE THREAD

**Issue by K6dev-bigD** [gkatzioura/BigDataWithScala#1]
getting following error 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/storm/topology/IRichSpout
	at com.gkatzioura.scala.storm.WordCountTopology.main(WordCountTopology.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.topology.IRichSpout
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

Process finished with exit code 1

**Comment by K6dev-bigD** [comment]
RESOLVED : 

1 > build.sbt 
libraryDependencies += "org.apache.storm" % "storm-core" % "0.9.3"
resolvers ++= Seq("clojars" at "http://clojars.org/repo/",
  "clojure-releases" at "http://build.clojure.org/releases")

Then change imports like : 
import backtype.storm.topology.base.BaseBasicBolt
import backtype.storm.topology.{BasicOutputCollector, OutputFieldsDeclarer}
import backtype.storm.tuple.{Fields, Tuple, Values}

2> SplitSentenceBolt : (was giving indexoutofbound exception )
resolved : 
override def execute(input: Tuple, collector: BasicOutputCollector): Unit = {

    val sentence:Array[String] = input.getString(0).split(" ")
    for(word <- sentence) {
        collector.emit(new Values(word))
    }
  }
